### PR TITLE
Dvxplorer support

### PR DESCRIPTION
**Pull request by llongi**
Cleanup README, boost issue, add DVXplorer support.

### CODE REVIEW

**Comment by guillermogb** [comment]
@jhidalgocarrio can you take care of this? I have no Dvxplorer to test. Thanks.
Thanks, @llongi

**Comment by llongi** [comment]
Can anyone take a look here? I can assure you it works, I do have some experience with the hardware in question. :-)

**Comment by jhidalgocarrio** [comment]
This PR looks good to me. However, I could not test it with a real camera.

**Review by jhidalgocarrio — APPROVED** [review]

**Comment by ziimiin14** [comment]
Hi @llongi ,
I recently plan to purchase dvxplorer lite instead of dvxplorer. I would like to know if the dvxplorer_ros_driver does support the lite version of dvxplorer before I make the purchase. Please let me know if you do the know answer. Thanks

**Comment by llongi** [comment]
Hello @ziimiin14, yes, both versions of the DVXplorer will work.

**Pull request merged**
