### PR TITLE
Updated davis_ros_driver and dvs_renderer to work with libcaer 3.0.0 and DAVIS346 Red Color

### LINKED ISSUE #77: Downgrade DAVIS revision
Hi,

Is there any method to downgrade DAVIS revision from 16 to 9912? or specifically 9912.

I had reflashed DAVIS device from 9912 to 16 for executing jAER toolkit, but this ROS package requires 16 revision. 

Thanks.

### PR DESCRIPTION
**Pull request by TSRyan**
Fixes #77.

Contributions:
- updated libcaer_catkin to pull version 3.0.0
- replaced references to IMU_RUN and FRAME_DELAY
- added support for various hardware filters:
  * skip
  * polarity
  * pixel
  * DVS ROI
  * APS ROI
- updated dvs_render to handle color images

### CODE REVIEW

**Comment by TSRyan** [comment]
Done.  After upgrading to logic version 18, things are still working.

**Comment by llongi** [comment]
Great. One more change: could you please depends on latest tag ff0e741fcfc0b59a41f87679d59620e3cc3b3a7e and then pass -DUDEV_INSTALL=0 to cmake, so that you can then drop the 'sudo' with 'make install'. It should then work like before, not requiring root because of the udev files.
Once that's done and you confirm it all works, I'll merge the PR.
Thank you for your work!

**Comment by TSRyan** [comment]
No problem! Changes are implemented and work.

**Comment by llongi** [comment]
Merged. Thank you for the excellent work!

**Pull request merged**
